name: laundry_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dash: ^1.0.5
  http: ^1.0.0
  url_launcher: ^6.1.11
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.0
  path_provider: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 800
  assets:
    - assets/images/01.jpg
    - assets/images/02.png
    - assets/images/facebook.png
    - assets/images/search.png
    - assets/images/03.png
    - assets/images/wash.jpg
    - assets/images/04.jpg
    - assets/images/05.png
    - assets/images/cat.png
    - assets/images/apple.png
    - assets/images/Mastercard.png
    - assets/images/paypal.png
    - assets/images/done.png
    - assets/images/trackorder.png
    - assets/images/process1.png
    - assets/images/process2.png
    - assets/images/process3.png
    - assets/images/icon1.png
    - assets/images/icon2.png
    - assets/images/icon3.png